name: updater
on:
  schedule:
  - cron: '10/30 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: update
      run : python3 TreeholeNotifier.py ${{ secrets.UID }} ${{ secrets.PASSWORD }}
    timeout-minutes: 5
  push:
    if: update success
    - name: push
      run : |
        git config --global user.email "zhuozhiyongde@126.com"
        git config --global user.name "Arthals"
        git add .
        git commit -m "update" -a
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.ACCESS_TOKEN}}
    - name: notify mobile
      run : exit 1
